spring:
  h2-console:
    enabled: true
    path: /h2
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
taco:
  orders:
    page: 0
    pageSize: 20